#!/usr/bin/env python3

import sys
import os
import re
import base64
from datetime import datetime
from pathlib import Path
from itertools import batched
from openai import OpenAI
import yaml

OPENAI_MODEL = "gpt-5.1"


collection_path = Path(__file__).parent / ".."
data_path = collection_path / "data"


api_key_file = os.getenv("OPENAI_API_KEY_FILE")
if api_key_file is None:
    sys.stderr.write("OPENAI_API_KEY_FILE env var is not set")
    sys.exit(1)

api_key_path = Path(api_key_file)
try:
    api_key = api_key_path.read_text().strip()
except OSError as e:
    sys.stderr.write(f"Can't read API key file {api_key_file}: {e}\n")
    sys.exit(1)

client = OpenAI(api_key=api_key)


prompt_path = collection_path / "prompt.txt"
try:
    prompt = prompt_path.read_text()
except OSError as e:
    sys.stderr.write(f"Can't AI prompt file {prompt_path}: {e}\n")
    sys.exit(1)


source_path = collection_path / "src"
commands = [
    #f"command: \"{c.strip()}\""
    c.strip()
    for file in source_path.iterdir()
    for c in re.split("\n\n+", file.read_text())
]
input = "\n---\n".join(commands)

#sys.stderr.write(input + "\n")
#sys.exit(0)

# Expand using AI
#
data = []
for batch in batched(commands, 10):
    response = client.responses.create(
        model=OPENAI_MODEL,
        instructions=prompt,
        input=input,
    )
    #sys.stderr.write(response.output_text)
    docs = yaml.safe_load_all(response.output_text)
    data.extend(docs)


# Deterministic field expansion
#
outdir = data_path / str(datetime.now().strftime("%Y%m%d%H%M%S"))
os.makedirs(outdir)

for doc in data:
    guid = base64.urlsafe_b64encode(os.urandom(8)).rstrip(b'=').decode()

    command = doc.get("command").strip()
    description = doc.get("description").strip()
    intention = doc.get("intention").strip()
    tool = doc.get("tool", "").strip()

    try:
        fst = command.split(" ")[0]
    except KeyError as e:
        sys.stderr.write(f"Can't read first command segment in:\n {doc}\n\n{e}\n")
        sys.exit(1)

    doc["guid"] = guid
    doc["aliases"] = [command]
    doc["command"] = command
    doc["description"] = description
    doc["intention"] = intention
    doc["requireSudo"] = fst == "sudo"

    if tool:
        parts = tool.split(" ")
        doc["tool"] = [
            " ".join(parts[:i+1])
            for i in range(len(parts))
        ]

    output = yaml.safe_dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    file = outdir / (guid + ".yaml")
    file.write_text(output)

    #sys.stdout.write(output + "---\n")


