#!/usr/bin/env python3
import sys
import os
import re
import base64
from datetime import datetime
from pathlib import Path
from itertools import batched
from openai import OpenAI
import yaml

OPENAI_MODEL = "gpt-5.1"
BATCH_SIZE = 10


capture_file = Path(sys.argv[1])
collection_path = Path(__file__).parent / ".."
data_path = collection_path / "data"


api_key_file = os.getenv("OPENAI_API_KEY_FILE")
if api_key_file is None:
    sys.stderr.write("OPENAI_API_KEY_FILE env var is not set")
    sys.exit(1)

api_key_path = Path(api_key_file)
try:
    api_key = api_key_path.read_text().strip()
except OSError as e:
    sys.stderr.write(f"Can't read API key file {api_key_file}: {e}\n")
    sys.exit(1)

client = OpenAI(api_key=api_key)


prompt_path = collection_path / "prompt.txt"
try:
    prompt = prompt_path.read_text()
except OSError as e:
    sys.stderr.write(f"Can't AI prompt file {prompt_path}: {e}\n")
    sys.exit(1)


capture = capture_file.read_text().strip()
if capture == "":
    sys.stderr.write("Capture file is empty.\n")
    sys.exit(1)

commands = [
    c.strip()
    for c in re.split("\n\n+", capture)
]
user_input = "\n---\n".join(commands)


# Expand using AI
#
command_count = len(commands)
batch_count = command_count // BATCH_SIZE + (1 if command_count % BATCH_SIZE else 0)

data = []
i = 1
for batch in batched(commands, BATCH_SIZE):
    sys.stderr.write(f"Sending AI query [{i}/{batch_count}].\n")
    i += 1

    response = client.responses.create(
        model=OPENAI_MODEL,
        instructions=prompt,
        input=user_input,
    )
    docs = yaml.safe_load_all(response.output_text)
    data.extend(docs)


# Deterministic field expansion
#
outdir = data_path / str(datetime.now().strftime("%Y%m%d%H%M%S"))
os.makedirs(outdir)
outdir = outdir.resolve()

for doc in data:
    guid = base64.urlsafe_b64encode(os.urandom(8)).rstrip(b'=').decode()

    command = doc.get("command").strip()
    description = doc.get("description").strip()
    intention = doc.get("intention").strip()
    tool = doc.get("tool", "").strip()
    nixos = doc.get("nixos", "").strip()

    try:
        fst = command.split(" ")[0]
    except KeyError as e:
        sys.stderr.write(f"Can't read first command segment in:\n {doc}\n\n{e}\n")
        sys.exit(1)

    doc["guid"] = guid
    doc["aliases"] = [command]
    doc["command"] = command
    doc["description"] = description
    doc["intention"] = intention
    doc["requireSudo"] = fst == "sudo"

    if tool:
        parts = tool.split(" ")
        doc["tool"] = [
            " ".join(parts[:i+1])
            for i in range(len(parts))
        ]

    if nixos:
        doc["nixos"] = nixos

    output = yaml.safe_dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    file = outdir / (guid + ".yaml")
    file.write_text(output)


sys.stderr.write(f"Data successfully generated in {outdir}.\n")

sys.stderr.write(f"Do you want to clear capture file? [y/N] ")
resp = input().strip().lower()

#if resp in ("y", "yes"):
capture_file.write_text("")
#    sys.stderr.write("Dump file cleared")

sys.stdout.write(f"{outdir}\n")
