#!/usr/bin/env bash
set -euo pipefail

: "${ROOT_DIR:="$(cd "$(dirname "$0")" && pwd)/.."}"

if OUTDIR=$("$ROOT_DIR/collections/commands/scripts/build-data"); then
    printf "%s:1: Need validation\n" "$OUTDIR"/*.yaml | vi -q -
fi
